import { useEffect, useState } from "react";
import { Link, Navigate, Outlet, Route, Routes, useLocation, useNavigate } from "react-router-dom";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { api, getToken, setToken } from "./lib/api";
import type { Expense } from "./types/api";

function RequireAuth() {
  const location = useLocation();
  if (!getToken()) return <Navigate to="/login" replace state={{ from: location.pathname }} />;
  return <AppShell />;
}

function AppShell() {
  const [mobileOpen, setMobileOpen] = useState(false);
  const location = useLocation();
  const navigate = useNavigate();
  const queryClient = useQueryClient();
  const { data: user } = useQuery({ queryKey: ["me"], queryFn: api.me });
  const nav = (path: string) => { setMobileOpen(false); navigate(path); };

  async function logout() {
    try { await api.logout(); } finally { setToken(null); queryClient.clear(); navigate("/login"); }
  }
  return <div className="app-shell">
    <aside className={`sidebar ${mobileOpen ? "open" : ""}`}>
      <div className="brand"><span className="brand-mark">L</span><div><strong>Ledgerly</strong><span>Personal finance</span></div></div>
      <nav><button className={location.pathname === "/" ? "active" : ""} onClick={() => nav("/")}>Overview</button><button className={location.pathname.startsWith("/expenses") ? "active" : ""} onClick={() => nav("/expenses")}>Expenses</button></nav>
      <div className="sidebar-bottom"><div className="user-chip"><span>{user?.email?.slice(0,1).toUpperCase() ?? "U"}</span><div><b>{user?.email ?? "Account"}</b><small>Personal account</small></div></div><button className="ghost-button" onClick={logout}>Sign out</button></div>
    </aside>
    <main className="main"><header className="topbar"><button className="menu-button" onClick={() => setMobileOpen(v => !v)} aria-label={mobileOpen ? "Close navigation" : "Open navigation"}>☰</button><div><span className="eyebrow">YOUR MONEY, CLEARLY</span><h1>{location.pathname === "/" ? "Overview" : "Expenses"}</h1></div>{location.pathname !== "/" && <Link className="primary-button compact" to="/expenses/new">Add expense</Link>}</header><Outlet /></main>
  </div>;
}

function AuthPage({ mode }: { mode: "login" | "register" }) {
  const navigate = useNavigate(); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  async function submit(e: React.FormEvent) { e.preventDefault(); setBusy(true); setError(""); try { const result = mode === "login" ? await api.login(email, password) : await api.register(email, password); setToken(result.access_token); navigate("/", { replace: true }); } catch (err) { setError(err instanceof Error ? err.message : "Unable to continue"); } finally { setBusy(false); } }
  return <div className="auth-page"><div className="auth-card"><div className="brand centered"><span className="brand-mark">L</span><div><strong>Ledgerly</strong><span>Personal finance</span></div></div><span className="eyebrow">WELCOME</span><h1>{mode === "login" ? "Back to your numbers." : "Start with clarity."}</h1><p className="muted">{mode === "login" ? "Sign in to manage your spending." : "Create a private account for your expenses."}</p>{error && <div className="error-banner" role="alert">{error}</div>}<form onSubmit={submit}><label>Email<input type="email" required value={email} onChange={e => setEmail(e.target.value)} placeholder="you@example.com" autoComplete={mode === "login" ? "email" : "email"} /></label><label>Password<input type="password" minLength={8} required value={password} onChange={e => setPassword(e.target.value)} placeholder="At least 8 characters" autoComplete={mode === "login" ? "current-password" : "new-password"} /></label><button className="primary-button full" disabled={busy}>{busy ? "Please wait…" : mode === "login" ? "Sign in" : "Create account"}</button></form><p className="auth-switch">{mode === "login" ? "New here?" : "Already have an account?"} <Link to={mode === "login" ? "/register" : "/login"}>{mode === "login" ? "Create an account" : "Sign in"}</Link></p></div></div>;
}

function Overview() {
  const { data, isLoading, isError } = useQuery({ queryKey: ["dashboard"], queryFn: api.dashboard });
  const format = (value: string) => `₹${Number(value).toLocaleString("en-IN", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
  if (isLoading) return <section className="content"><div className="loading-panel">Loading your overview…</div></section>;
  if (isError || !data) return <section className="content"><div className="error-banner" role="alert">We couldn’t load your dashboard. Refresh and try again.</div></section>;
  const maxTrend = Math.max(...data.monthly_trends.map(x => Number(x.amount)), 1);
  return <section className="content"><div className="hero-grid"><div className="metric-card feature"><span>Total spending</span><strong>{format(data.total_spending)}</strong><small>Across all recorded expenses</small></div><div className="metric-card"><span>This month</span><strong>{format(data.current_month_spending)}</strong><small>Since the 1st of this month</small></div><div className="metric-card"><span>Categories</span><strong>{data.by_category.length}</strong><small>Active spending categories</small></div></div><div className="dashboard-grid"><section className="panel"><div className="panel-head"><div><span className="eyebrow">TREND</span><h2>Monthly spending</h2></div><Link to="/expenses" className="text-link">View expenses →</Link></div>{data.monthly_trends.length ? <div className="trend-chart">{data.monthly_trends.map(item => <div className="bar-col" key={item.month}><div className="bar-wrap"><div className="bar" style={{height: `${Math.max(7, Number(item.amount) / maxTrend * 100)}%`}} title={format(item.amount)} /></div><span>{item.month.slice(5)}</span></div>)}</div> : <div className="empty-state">Add your first expense to see trends.</div>}</section><section className="panel"><div className="panel-head"><div><span className="eyebrow">BREAKDOWN</span><h2>By category</h2></div></div>{data.by_category.length ? <div className="category-list">{data.by_category.map(item => <div className="category-row" key={item.category}><div><span className="dot" />{item.category}</div><b>{format(item.amount)}</b></div>)}</div> : <div className="empty-state">No categories yet.</div>}</section></div><section className="panel"><div className="panel-head"><div><span className="eyebrow">RECENT</span><h2>Latest expenses</h2></div><Link to="/expenses" className="text-link">Open ledger →</Link></div><ExpenseTable items={data.recent_expenses} compact /></section></section>;
}

function ExpenseTable({ items, compact = false }: { items: Expense[]; compact?: boolean }) {
  const navigate = useNavigate(); const [deleting, setDeleting] = useState<string | null>(null); const [error, setError] = useState(""); const queryClient = useQueryClient();
  const format = (v: string) => `₹${Number(v).toLocaleString("en-IN", {minimumFractionDigits:2, maximumFractionDigits:2})}`;
  async function remove(id: string) { if (!confirm("Delete this expense? This cannot be undone.")) return; setDeleting(id); setError(""); try { await api.deleteExpense(id); queryClient.invalidateQueries({ queryKey: ["expenses"] }); queryClient.invalidateQueries({ queryKey: ["dashboard"] }); } catch (e) { setError(e instanceof Error ? e.message : "Couldn’t delete expense"); } finally { setDeleting(null); } }
  if (!items.length) return <div className="empty-state"><strong>No expenses yet.</strong><span>Track your first purchase to get started.</span><Link className="primary-button compact" to="/expenses/new">Add expense</Link></div>;
  return <>{error && <div className="error-banner" role="alert">{error}</div>}<div className="table-wrap"><table><thead><tr><th>Date</th><th>Description</th><th>Category</th><th>Amount</th>{!compact && <th />}</tr></thead><tbody>{items.map(item => <tr key={item.id}><td>{item.date}</td><td><b>{item.description}</b>{item.notes && <small>{item.notes}</small>}</td><td><span className="tag">{item.category.name}</span></td><td className="amount">{format(item.amount)}</td>{!compact && <td className="actions"><button onClick={() => navigate(`/expenses/${item.id}/edit`)}>Edit</button><button disabled={deleting === item.id} onClick={() => remove(item.id)}>{deleting === item.id ? "Deleting…" : "Delete"}</button></td>}</tr>)}</tbody></table></div></>;
}

function Expenses() {
  const [search, setSearch] = useState(""); const [category, setCategory] = useState(""); const [from, setFrom] = useState(""); const [to, setTo] = useState(""); const [page, setPage] = useState(1); const [sort, setSort] = useState("date");
  const params = new URLSearchParams({ page: String(page), page_size: "12", sort, direction: "desc" }); if (search) params.set("search", search); if (category) params.set("category", category); if (from) params.set("date_from", from); if (to) params.set("date_to", to);
  const query = useQuery({ queryKey: ["expenses", params.toString()], queryFn: () => api.expenses(params) });
  const [importBusy, setImportBusy] = useState(false); const [notice, setNotice] = useState(""); const [error, setError] = useState("");
  async function importFile(file: File) { setImportBusy(true); setNotice(""); setError(""); try { const result = await api.importCsv(file); setNotice(`Imported ${result.imported}; skipped ${result.skipped_duplicates} duplicate${result.skipped_duplicates === 1 ? "" : "s"}; ${result.failed} invalid.`); query.refetch(); } catch (e) { setError(e instanceof Error ? e.message : "Import failed"); } finally { setImportBusy(false); } }
  async function exportCsv() { setNotice(""); setError(""); try { const filters = new URLSearchParams(); if (from) filters.set("date_from", from); if (to) filters.set("date_to", to); const blob = await api.exportCsv(filters); const url = URL.createObjectURL(blob); const a = document.createElement("a"); a.href = url; a.download = "ledgerly-expenses.csv"; document.body.appendChild(a); a.click(); a.remove(); URL.revokeObjectURL(url); setNotice("CSV export started."); } catch (e) { setError(e instanceof Error ? e.message : "Export failed"); } }
  const categories = ["Food","Transport","Housing","Shopping","Health","Entertainment","Bills","Other"];
  return <section className="content"><div className="toolbar"><div className="search-box"><span aria-hidden="true">⌕</span><input value={search} onChange={e => {setSearch(e.target.value); setPage(1)}} placeholder="Search description, notes or category" aria-label="Search expenses" /></div><select value={category} onChange={e => {setCategory(e.target.value); setPage(1)}} aria-label="Filter by category"><option value="">All categories</option>{categories.map(c => <option key={c}>{c}</option>)}</select><input type="date" value={from} onChange={e => {setFrom(e.target.value); setPage(1)}} aria-label="Filter from date" /><input type="date" value={to} onChange={e => {setTo(e.target.value); setPage(1)}} aria-label="Filter to date" /><select value={sort} onChange={e => setSort(e.target.value)} aria-label="Sort expenses"><option value="date">Newest</option><option value="amount">Amount</option><option value="description">Description</option></select></div><div className="action-strip"><Link className="primary-button compact" to="/expenses/new">+ Add expense</Link><button className="secondary-button compact" onClick={exportCsv}>Export CSV</button><label className={`secondary-button compact file-label ${importBusy ? "disabled" : ""}`}>{importBusy ? "Importing…" : "Import CSV"}<input type="file" accept=".csv,text/csv" disabled={importBusy} onChange={e => { const file = e.target.files?.[0]; if (file) { void importFile(file); e.currentTarget.value = ""; } }} aria-label="Choose CSV file to import" /></label></div>{notice && <div className="notice" role="status">{notice}</div>}{error && <div className="error-banner" role="alert">{error}</div>}{query.isLoading ? <div className="loading-panel">Loading expenses…</div> : query.isError ? <div className="error-banner" role="alert">Couldn’t load expenses. Check your filters and try again.</div> : <div className="panel"><div className="panel-head"><div><span className="eyebrow">LEDGER</span><h2>{query.data?.total ?? 0} expenses</h2></div></div><ExpenseTable items={query.data?.items ?? []} /><div className="pager"><span>Page {query.data?.page ?? page} of {query.data?.pages ?? 1}</span><div><button disabled={page <= 1} onClick={() => setPage(p => p - 1)} aria-label="Previous page">←</button><button disabled={page >= (query.data?.pages ?? 1)} onClick={() => setPage(p => p + 1)} aria-label="Next page">→</button></div></div></div>}</section>;
}

function ExpenseForm({ edit = false }: { edit?: boolean }) {
  const navigate = useNavigate(); const location = useLocation(); const id = edit ? location.pathname.split("/")[2] : undefined; const existing = useQuery({ queryKey: ["expense", id], queryFn: () => api.expense(id!), enabled: Boolean(id) });
  const [amount, setAmount] = useState(""); const [description, setDescription] = useState(""); const [category, setCategory] = useState("Food"); const [date, setDate] = useState(new Date().toISOString().slice(0,10)); const [notes, setNotes] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const queryClient = useQueryClient();
  useEffect(() => { if (existing.data) { setAmount(existing.data.amount); setDescription(existing.data.description); setCategory(existing.data.category.name); setDate(existing.data.date); setNotes(existing.data.notes ?? ""); } }, [existing.data]);
  async function submit(e: React.FormEvent) { e.preventDefault(); setBusy(true); setError(""); try { const body = { amount, description, category, date, notes: notes || null }; if (edit) await api.updateExpense(id!, body); else await api.createExpense(body); queryClient.invalidateQueries({ queryKey: ["expenses"] }); queryClient.invalidateQueries({ queryKey: ["dashboard"] }); navigate("/expenses"); } catch (e) { setError(e instanceof Error ? e.message : "Couldn’t save expense"); } finally { setBusy(false); } }
  if (edit && existing.isLoading) return <section className="content"><div className="loading-panel">Loading expense…</div></section>;
  if (edit && existing.isError) return <section className="content"><div className="error-banner" role="alert">Couldn’t load that expense. It may have been deleted.</div><Link className="secondary-button compact" to="/expenses">Back to expenses</Link></section>;
  return <section className="content"><div className="form-panel"><div className="panel-head"><div><span className="eyebrow">{edit ? "EDIT" : "NEW ENTRY"}</span><h2>{edit ? "Update expense" : "Record an expense"}</h2></div></div>{error && <div className="error-banner" role="alert">{error}</div>}<form className="expense-form" onSubmit={submit}><div className="form-grid"><label>Amount<input inputMode="decimal" required value={amount} onChange={e => setAmount(e.target.value)} placeholder="0.00" aria-label="Expense amount" /></label><label>Date<input type="date" required value={date} onChange={e => setDate(e.target.value)} /></label><label>Description<input required maxLength={200} value={description} onChange={e => setDescription(e.target.value)} placeholder="What did you spend on?" /></label><label>Category<select value={category} onChange={e => setCategory(e.target.value)}>{["Food","Transport","Housing","Shopping","Health","Entertainment","Bills","Other"].map(c => <option key={c}>{c}</option>)}</select></label><label className="wide">Notes<textarea value={notes} onChange={e => setNotes(e.target.value)} maxLength={2000} rows={5} placeholder="Optional context, merchant, or reason" /></label></div><div className="form-actions"><button type="button" className="secondary-button" onClick={() => navigate("/expenses")}>Cancel</button><button className="primary-button" disabled={busy}>{busy ? "Saving…" : edit ? "Save changes" : "Add expense"}</button></div></form></div></section>;
}

export default function App() { return <Routes><Route path="/login" element={<AuthPage mode="login" />} /><Route path="/register" element={<AuthPage mode="register" />} /><Route element={<RequireAuth />}><Route path="/" element={<Overview />} /><Route path="/expenses" element={<Expenses />} /><Route path="/expenses/new" element={<ExpenseForm />} /><Route path="/expenses/:id/edit" element={<ExpenseForm edit />} /></Route><Route path="*" element={<Navigate to="/" replace />} /></Routes>; }
